// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7f3HeOoQhcFjRPHG0rtFAKU68PqLnliA',
    appId: '1:339990848950:web:e75ea2f4c9a7ad680e8d17',
    messagingSenderId: '339990848950',
    projectId: 'twitterclonetute-18b5b',
    authDomain: 'twitterclonetute-18b5b.firebaseapp.com',
    storageBucket: 'twitterclonetute-18b5b.firebasestorage.app',
    measurementId: 'G-TTE8S06WFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCABOPxgPxounGpZ58PxG00hCmSsrX8310',
    appId: '1:339990848950:android:ad9f52227bd8fe040e8d17',
    messagingSenderId: '339990848950',
    projectId: 'twitterclonetute-18b5b',
    storageBucket: 'twitterclonetute-18b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSIH3r6256u_jwF_j6hIEyJkrnU_ZgbmY',
    appId: '1:339990848950:ios:4308dea5accca6dd0e8d17',
    messagingSenderId: '339990848950',
    projectId: 'twitterclonetute-18b5b',
    storageBucket: 'twitterclonetute-18b5b.firebasestorage.app',
    iosBundleId: 'com.example.twitterclone',
  );
}
